# Generated by Django 4.1.5 on 2023-05-07 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rfidtable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfidtable',
            old_name='First_Name',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='rfidtable',
            old_name='Last_Name',
            new_name='LastName',
        ),
    ]
