# Generated by Django 4.1.5 on 2023-05-07 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_first_name_rfidtable_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfidtable',
            old_name='FirstName',
            new_name='FName',
        ),
        migrations.RenameField(
            model_name='rfidtable',
            old_name='LastName',
            new_name='LName',
        ),
    ]
