# Generated by Django 4.1.5 on 2023-05-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_firstname_rfidtable_fname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='usertable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FName', models.CharField(max_length=30)),
                ('LName', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.BigIntegerField()),
                ('DOB', models.DateField()),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
