# Generated by Django 4.1.5 on 2023-05-07 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_usertable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rfidtable',
        ),
    ]
